"""Prometheus metrics registry — shared across API and worker processes.

Import these counters/histograms from any module to record observations.
They are auto-registered with prometheus_client on import.
"""

from __future__ import annotations

from prometheus_client import Counter, Histogram

# Pipeline throughput
ideas_generated = Counter("ideas_generated_total", "Ideas generated by the swarm")
ideas_passed = Counter("ideas_passed_total", "Ideas that passed the money filter")
ideas_rejected = Counter(
    "ideas_rejected_total",
    "Ideas rejected by money filter",
    ["reject_reason"],
)
deployments = Counter("deployments_total", "Successful MVP deployments")
deployment_failures = Counter("deployment_failures_total", "Failed MVP deployments")

# Distribution
posts_published = Counter(
    "posts_published_total",
    "Distribution posts published",
    ["platform"],
)

# Revenue
revenue_usd = Counter("revenue_usd_total", "Total revenue received in USD")
payments_received = Counter("payments_received_total", "Number of payment events recorded")
signups_received = Counter("signups_received_total", "Number of signup events recorded")

# Cycle timing
cycle_duration_seconds = Histogram(
    "cycle_duration_seconds",
    "Full pipeline cycle duration",
    buckets=[30, 60, 120, 300, 600, 900, 1800, 3600],
)

# Weight updates
weight_updates = Counter("weight_updates_total", "Learning agent weight update events")
